// utils/styles.js

// --- STYLE UMUM (styles) ---
export const styles = {
    container: {
        fontFamily: 'Arial, sans-serif',
        display: 'flex',
        flexDirection: 'column',
        alignItems: 'center',
        minHeight: '100vh',
        backgroundColor: '#DBB5EE', 
        padding: '20px',
    },
    header: {
        color: '#333',
        marginBottom: '20px',
    },
    contentBox: {
        backgroundColor: '#fff',
        border: '5px solid #000', 
        borderRadius: '10px',
        boxShadow: '0 4px 20px rgba(0, 0, 0, 0.3)',
        padding: '20px',
        maxWidth: '600px', 
        width: '100%',
        minHeight: '400px',
        display: 'flex',
        flexDirection: 'column',
        alignItems: 'center',
    },
    cameraArea: {
        width: '100%',
        display: 'flex',
        flexDirection: 'column',
        alignItems: 'center',
    },
    // DSLR Camera Interface
    dslrTopPanel: {
        width: '100%',
        height: '80px',
        background: 'linear-gradient(135deg, #2c2c2c 0%, #1a1a1a 50%, #0f0f0f 100%)',
        borderRadius: '20px 20px 10px 10px',
        display: 'flex',
        justifyContent: 'space-between',
        alignItems: 'center',
        padding: '0 25px',
        marginBottom: '3px',
        boxShadow: '0 8px 25px rgba(0, 0, 0, 0.4), inset 0 1px 0 rgba(255, 255, 255, 0.1)',
        border: '1px solid rgba(255, 255, 255, 0.05)',
    },
    dslrModeDial: {
        width: '120px',
        height: '120px',
        background: 'radial-gradient(circle, #3a3a3a, #1a1a1a)',
        borderRadius: '50%',
        position: 'relative',
        border: '3px solid #2a2a2a',
        boxShadow: '0 4px 15px rgba(0, 0, 0, 0.5), inset 0 2px 4px rgba(255, 255, 255, 0.1)',
        display: 'flex',
        justifyContent: 'center',
        alignItems: 'center',
    },
    dialMarking: {
        position: 'absolute',
        color: '#888',
        fontSize: '10px',
        fontWeight: 'bold',
        textShadow: '0 1px 2px rgba(0, 0, 0, 0.5)',
    },
    dialMarkingActive: {
        position: 'absolute',
        color: '#ff4444',
        fontSize: '12px',
        fontWeight: 'bold',
        textShadow: '0 0 5px rgba(255, 68, 68, 0.5)',
    },
    dslrShutterButton: {
        width: '60px',
        height: '60px',
        position: 'relative',
    },
    shutterButton: {
        width: '50px',
        height: '50px',
        background: 'radial-gradient(circle, #e74c3c, #c0392b)',
        borderRadius: '50%',
        border: '2px solid #8b0000',
        boxShadow: '0 6px 20px rgba(231, 76, 60, 0.4), inset 0 2px 4px rgba(255, 255, 255, 0.2)',
        position: 'absolute',
        top: '5px',
        left: '5px',
    },
    dslrInfoPanel: {
        display: 'flex',
        flexDirection: 'column',
        alignItems: 'flex-end',
        gap: '5px',
    },
    infoDisplay: {
        color: '#00ff00',
        fontSize: '14px',
        fontWeight: 'bold',
        fontFamily: 'monospace',
        textShadow: '0 0 8px rgba(0, 255, 0, 0.5)',
        background: 'rgba(0, 0, 0, 0.7)',
        padding: '4px 8px',
        borderRadius: '3px',
    },
    infoSubtext: {
        color: '#aaa',
        fontSize: '11px',
        fontFamily: 'monospace',
        textShadow: '0 1px 2px rgba(0, 0, 0, 0.5)',
    },
    dslrViewfinderArea: {
        width: '100%',
        background: 'linear-gradient(to bottom, #1a1a1a, #0f0f0f)',
        padding: '15px',
        borderRadius: '10px 10px 20px 20px',
        boxShadow: 'inset 0 4px 15px rgba(0, 0, 0, 0.3)',
    },
    viewfinderFrame: {
        width: '100%',
        minHeight: '60px',
        background: 'linear-gradient(135deg, rgba(0, 0, 0, 0.8), rgba(20, 20, 20, 0.9))',
        border: '2px solid #333',
        borderRadius: '8px',
        display: 'flex',
        justifyContent: 'space-between',
        alignItems: 'center',
        padding: '15px 20px',
        boxShadow: 'inset 0 2px 8px rgba(0, 0, 0, 0.5)',
    },
    dslrCountdown: {
        display: 'flex',
        justifyContent: 'center',
        alignItems: 'center',
    },
    countdownCircle: {
        width: '45px',
        height: '45px',
        background: 'radial-gradient(circle, #ff4444, #cc0000)',
        borderRadius: '50%',
        display: 'flex',
        justifyContent: 'center',
        alignItems: 'center',
        boxShadow: '0 4px 15px rgba(255, 68, 68, 0.4), inset 0 2px 4px rgba(255, 255, 255, 0.3)',
        animation: 'pulse 1s infinite',
        border: '2px solid #8b0000',
    },
    countdownNumber: {
        color: 'white',
        fontSize: '24px',
        fontWeight: 'bold',
        textShadow: '0 2px 4px rgba(0, 0, 0, 0.5)',
    },
    dslrCameraBody: {
        width: '100%',
        background: 'linear-gradient(135deg, #1a1a1a 0%, #2c2c2c 50%, #1a1a1a 100%)',
        borderRadius: '0 0 20px 20px',
        padding: '15px',
        boxShadow: '0 8px 30px rgba(0, 0, 0, 0.4), inset 0 1px 0 rgba(255, 255, 255, 0.05)',
        border: '1px solid rgba(255, 255, 255, 0.05)',
    },
    // DSLR Control Panel
    dslrControlPanel: {
        width: '100%',
        background: 'linear-gradient(135deg, #1a1a1a 0%, #2c2c2c 50%, #1a1a1a 100%)',
        borderRadius: '0 0 20px 20px',
        padding: '25px',
        boxShadow: '0 8px 30px rgba(0, 0, 0, 0.4), inset 0 1px 0 rgba(255, 255, 255, 0.05)',
        border: '1px solid rgba(255, 255, 255, 0.05)',
    },
    controlPanelHeader: {
        display: 'flex',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: '25px',
        paddingBottom: '15px',
        borderBottom: '1px solid rgba(255, 255, 255, 0.1)',
    },
    controlPanelTitle: {
        color: '#00ff00',
        fontSize: '16px',
        fontWeight: 'bold',
        fontFamily: 'monospace',
        textShadow: '0 0 8px rgba(0, 255, 0, 0.5)',
        letterSpacing: '2px',
    },
    controlPanelIndicator: {
        color: '#00ff00',
        fontSize: '12px',
        fontFamily: 'monospace',
        textShadow: '0 0 5px rgba(0, 255, 0, 0.5)',
        animation: 'pulse 2s infinite',
    },
    layoutSelector: {
        marginBottom: '30px',
    },
    selectorLabel: {
        color: '#aaa',
        fontSize: '11px',
        fontFamily: 'monospace',
        textTransform: 'uppercase',
        letterSpacing: '1px',
        marginBottom: '10px',
        textShadow: '0 1px 2px rgba(0, 0, 0, 0.5)',
    },
    customDropdown: {
        position: 'relative',
        width: '100%',
        marginBottom: '15px',
    },
    dropdownSelect: {
        width: '100%',
        padding: '15px 40px 15px 15px',
        background: 'linear-gradient(135deg, #2a2a2a, #1a1a1a)',
        border: '2px solid #333',
        borderRadius: '8px',
        color: '#00ff00',
        fontSize: '14px',
        fontFamily: 'monospace',
        fontWeight: 'bold',
        textShadow: '0 0 5px rgba(0, 255, 0, 0.3)',
        appearance: 'none',
        cursor: 'pointer',
        boxShadow: 'inset 0 2px 8px rgba(0, 0, 0, 0.3), 0 4px 15px rgba(0, 0, 0, 0.2)',
        transition: 'all 0.3s ease',
    },
    dropdownArrow: {
        position: 'absolute',
        right: '15px',
        top: '50%',
        transform: 'translateY(-50%)',
        color: '#00ff00',
        fontSize: '12px',
        pointerEvents: 'none',
        textShadow: '0 0 5px rgba(0, 255, 0, 0.5)',
    },
    modeInfo: {
        display: 'flex',
        gap: '20px',
        justifyContent: 'center',
    },
    modeInfoText: {
        color: '#888',
        fontSize: '11px',
        fontFamily: 'monospace',
        background: 'rgba(0, 0, 0, 0.5)',
        padding: '4px 8px',
        borderRadius: '4px',
        border: '1px solid #333',
    },
    startButtonContainer: {
        display: 'flex',
        justifyContent: 'center',
        marginTop: '20px',
    },
    dslrStartButton: {
        display: 'flex',
        alignItems: 'center',
        gap: '15px',
        padding: '20px 40px',
        background: 'linear-gradient(135deg, #e74c3c, #c0392b)',
        border: '2px solid #8b0000',
        borderRadius: '12px',
        cursor: 'pointer',
        boxShadow: '0 8px 25px rgba(231, 76, 60, 0.4), inset 0 2px 4px rgba(255, 255, 255, 0.2)',
        transition: 'all 0.3s ease',
    },
    buttonIcon: {
        fontSize: '24px',
        filter: 'drop-shadow(0 2px 4px rgba(0, 0, 0, 0.3))',
    },
    buttonText: {
        display: 'flex',
        flexDirection: 'column',
        alignItems: 'flex-start',
    },
    buttonMainText: {
        color: 'white',
        fontSize: '16px',
        fontWeight: 'bold',
        textShadow: '0 2px 4px rgba(0, 0, 0, 0.5)',
        letterSpacing: '1px',
    },
    buttonSubText: {
        color: 'rgba(255, 255, 255, 0.8)',
        fontSize: '12px',
        fontFamily: 'monospace',
        textShadow: '0 1px 2px rgba(0, 0, 0, 0.5)',
    },
    // Result Area Styles
    resultArea: {
        width: '100%',
        display: 'flex',
        flexDirection: 'column',
        alignItems: 'center',
    },
    successText: {
        color: '#27ae60',
        fontSize: '18px',
        fontWeight: 'bold',
        marginBottom: '15px',
        textShadow: '0 1px 2px rgba(0, 0, 0, 0.1)',
    },
    canvasResult: {
        width: '500px',
        height: '500px',
        border: '3px solid #000',
        borderRadius: '8px',
        boxShadow: '0 4px 15px rgba(0, 0, 0, 0.2)',
        maxWidth: '100%',
        display: 'block',
        objectFit: 'contain',
    },
    downloadButton: {
        padding: '12px 24px',
        background: 'linear-gradient(135deg, #27ae60, #229954)',
        color: 'white',
        border: 'none',
        borderRadius: '8px',
        fontSize: '14px',
        fontWeight: 'bold',
        cursor: 'pointer',
        marginRight: '10px',
        boxShadow: '0 4px 15px rgba(39, 174, 96, 0.3)',
        transition: 'all 0.3s ease',
    },
    retakeButton: {
        padding: '12px 24px',
        background: 'linear-gradient(135deg, #e67e22, #d35400)',
        color: 'white',
        border: 'none',
        borderRadius: '8px',
        fontSize: '14px',
        fontWeight: 'bold',
        cursor: 'pointer',
        boxShadow: '0 4px 15px rgba(230, 126, 34, 0.3)',
        transition: 'all 0.3s ease',
    },
    // Status text untuk viewfinder
    statusText: {
        color: '#00ff00',
        fontSize: '14px',
        fontWeight: 'bold',
        fontFamily: 'monospace',
        textShadow: '0 0 5px rgba(0, 255, 0, 0.5)',
    },
};

// --- STYLE KHUSUS KAMERA (cameraStyles) ---
export const cameraStyles = {
    container: {
        width: '100%',
        textAlign: 'center',
    },
    videoContainer: {
        width: '100%',
        height: '400px',
        position: 'relative',
        overflow: 'hidden',
        borderRadius: '15px',
        background: 'linear-gradient(135deg, #2c3e50 0%, #34495e 50%, #2c3e50 100%)',
        padding: '6px',
        marginBottom: '20px',
        boxShadow: '0 8px 32px rgba(0, 0, 0, 0.3), inset 0 1px 0 rgba(255, 255, 255, 0.1)',
        border: '1px solid rgba(255, 255, 255, 0.1)',
    },
    videoFeed: {
        position: 'absolute',
        top: '6px',
        left: '6px',
        right: '6px',
        bottom: '6px',
        width: 'calc(100% - 12px)',
        height: 'calc(100% - 12px)',
        objectFit: 'cover',
        borderRadius: '10px',
        border: '2px solid #1a1a1a',
    },
    viewfinderOverlay: {
        position: 'absolute',
        top: 0,
        left: 0,
        width: '100%',
        height: '100%',
        pointerEvents: 'none',
        zIndex: 10,
    },
    cornerTopLeft: {
        position: 'absolute',
        top: '20px',
        left: '20px',
        width: '40px',
        height: '40px',
        borderTop: '3px solid #ff4444',
        borderLeft: '3px solid #ff4444',
    },
    cornerTopRight: {
        position: 'absolute',
        top: '20px',
        right: '20px',
        width: '40px',
        height: '40px',
        borderTop: '3px solid #ff4444',
        borderRight: '3px solid #ff4444',
    },
    cornerBottomLeft: {
        position: 'absolute',
        bottom: '20px',
        left: '20px',
        width: '40px',
        height: '40px',
        borderBottom: '3px solid #ff4444',
        borderLeft: '3px solid #ff4444',
    },
    cornerBottomRight: {
        position: 'absolute',
        bottom: '20px',
        right: '20px',
        width: '40px',
        height: '40px',
        borderBottom: '3px solid #ff4444',
        borderRight: '3px solid #ff4444',
    },
    focusIndicator: {
        position: 'absolute',
        top: '50%',
        left: '50%',
        transform: 'translate(-50%, -50%)',
    },
    focusRing: {
        width: '60px',
        height: '60px',
        border: '2px solid rgba(255, 255, 255, 0.8)',
        borderRadius: '50%',
        boxShadow: '0 0 10px rgba(255, 255, 255, 0.5)',
    },
    cameraInfo: {
        position: 'absolute',
        top: '20px',
        left: '20px',
        display: 'flex',
        flexDirection: 'column',
        gap: '5px',
    },
    recIndicator: {
        color: '#ff4444',
        fontSize: '12px',
        fontWeight: 'bold',
        textShadow: '0 0 5px rgba(255, 68, 68, 0.5)',
    },
    cameraMode: {
        color: 'white',
        fontSize: '10px',
        fontWeight: 'bold',
        backgroundColor: 'rgba(0, 0, 0, 0.5)',
        padding: '2px 6px',
        borderRadius: '3px',
    },
    cameraBody: {
        position: 'absolute',
        top: '-12px',
        right: '15px',
        display: 'flex',
        alignItems: 'center',
        gap: '6px',
    },
    cameraLens: {
        width: '35px',
        height: '35px',
        background: 'radial-gradient(circle, #1a1a1a 30%, #333 60%, #555 100%)',
        borderRadius: '50%',
        border: '3px solid #222',
        boxShadow: '0 2px 8px rgba(0, 0, 0, 0.5), inset 0 1px 2px rgba(255, 255, 255, 0.2)',
    },
    cameraShutter: {
        width: '20px',
        height: '20px',
        background: 'linear-gradient(135deg, #c0392b, #e74c3c)',
        borderRadius: '50%',
        border: '2px solid #8b0000',
        boxShadow: '0 2px 4px rgba(0, 0, 0, 0.3)',
        position: 'relative',
        top: '-5px',
    },
    cameraFlash: {
        width: '15px',
        height: '10px',
        background: 'linear-gradient(to bottom, #ecf0f1, #bdc3c7)',
        borderRadius: '2px',
        border: '1px solid #95a5a6',
        boxShadow: '0 1px 3px rgba(0, 0, 0, 0.2)',
    },
    cameraControls: {
        position: 'absolute',
        bottom: '15px',
        right: '20px',
        display: 'flex',
        gap: '12px',
    },
    controlButton: {
        width: '8px',
        height: '8px',
        background: 'radial-gradient(circle, #34495e, #2c3e50)',
        borderRadius: '50%',
        border: '1px solid #1a1a1a',
        boxShadow: '0 1px 2px rgba(0, 0, 0, 0.3)',
    },
    loadingContainer: {
        display: 'flex',
        flexDirection: 'column',
        alignItems: 'center',
        justifyContent: 'center',
        padding: '40px',
    },
    loadingIcon: {
        fontSize: '48px',
        marginBottom: '10px',
        animation: 'pulse 2s infinite',
    },
}

// Tambahkan CSS animation untuk pulse
if (typeof document !== 'undefined') {
    const style = document.createElement('style');
    style.textContent = `
        @keyframes pulse {
            0% { opacity: 1; }
            50% { opacity: 0.6; }
            100% { opacity: 1; }
        }
    `;
    document.head.appendChild(style);
}